name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (if you have any build steps like minifying or bundling)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies (if applicable)
    - name: Install dependencies
      run: |
        npm install  # Or any build tools you need, e.g., npm run build

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
        publish_dir: ./  # Path to the folder you want to deploy, usually the root directory
        publish_branch: gh-pages  # The branch GitHub Pages will use
